# =============================================================
# vFinacc — gRPC Client for vKernel IPC
# GovernanceID: vfinacc.3.0 (gRPC Client)
# Stubs generated from protos/kernel.proto at Docker build time.
# =============================================================
from __future__ import annotations

import json
import logging
import os
from typing import Optional

log = logging.getLogger(__name__)

# gRPC imports — stubs generated by Dockerfile from protos/kernel.proto
try:
    import grpc
    from app.grpc import kernel_pb2, kernel_pb2_grpc  # type: ignore[import]
    GRPC_AVAILABLE = True
except ImportError:
    log.warning("gRPC stubs not found (run inside Docker to auto-generate). gRPC disabled.")
    GRPC_AVAILABLE = False


class KernelGrpcClient:
    """
    Client for vKernel's KernelService gRPC API.
    Connects to KERNEL_GRPC_URL (default: vkernel:9090).
    Gracefully degrades if vKernel gRPC is unreachable.
    """

    def __init__(self) -> None:
        host = os.environ.get("KERNEL_GRPC_HOST", "vkernel")
        port = os.environ.get("KERNEL_GRPC_PORT", "9090")
        target = os.environ.get("KERNEL_GRPC_URL", f"{host}:{port}")
        self._channel: Optional[object] = None
        self._stub: Optional[object] = None
        if GRPC_AVAILABLE:
            try:
                self._channel = grpc.insecure_channel(target)
                self._stub = kernel_pb2_grpc.KernelServiceStub(self._channel)
                log.info("gRPC client initialized → %s", target)
            except Exception as exc:
                log.warning("gRPC client init failed: %s", exc)

    # ---- Public API ————————————————————————————————————————

    def ping(self) -> dict:
        """Health check: call Kernel's Ping RPC."""
        if not self._stub:
            return {"status": "GRPC_UNAVAILABLE"}
        try:
            req  = kernel_pb2.PingRequest(from_field="vfinacc")  # type: ignore
            resp = self._stub.Ping(req, timeout=2)  # type: ignore
            return {
                "status":    resp.status,
                "version":   resp.version,
                "uptime_ms": resp.uptime_ms,
            }
        except Exception as exc:
            log.warning("gRPC Ping failed: %s", exc)
            return {"status": "ERROR", "detail": str(exc)}

    def publish_event(self, event_type: str, payload: dict,
                      correlation_id: str = "") -> dict:
        """Publish a domain event to the kernel event bus via gRPC."""
        if not self._stub:
            return {"status": "GRPC_UNAVAILABLE"}
        try:
            req = kernel_pb2.GrpcEventRequest(  # type: ignore
                source="vfinacc",
                event_type=event_type,
                event_version="1.0",
                payload_json=json.dumps(payload),
                correlation_id=correlation_id,
            )
            resp = self._stub.PublishEvent(req, timeout=3)  # type: ignore
            return {"event_id": resp.event_id, "status": resp.status}
        except Exception as exc:
            log.warning("gRPC PublishEvent failed: %s", exc)
            return {"status": "ERROR", "detail": str(exc)}

    def get_installed_apps(self, tenant_id: str = "") -> list[dict]:
        """Query the App Registry from Kernel."""
        if not self._stub:
            return []
        try:
            req  = kernel_pb2.GetAppsRequest(tenant_id=tenant_id)  # type: ignore
            resp = self._stub.GetInstalledApps(req, timeout=2)  # type: ignore
            return [
                {
                    "app_id":       app.app_id,
                    "display_name": app.display_name,
                    "version":      app.version,
                    "status":       app.status,
                }
                for app in resp.apps
            ]
        except Exception as exc:
            log.warning("gRPC GetInstalledApps failed: %s", exc)
            return []

    def close(self) -> None:
        if self._channel:
            try:
                self._channel.close()  # type: ignore
            except Exception:
                pass


# Module-level singleton — created once at import time.
kernel_client = KernelGrpcClient()
