apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
stringData:
  username: {{ .Values.postgresql.username }}
  password: {{ .Values.postgresql.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secret
type: Opaque
stringData:
  jwt-secret: {{ .Values.vkernel.env.JWT_SECRET }}
